### ISSUE TITLE
Annotaion 기반 Swagger로 전환

### ISSUE THREAD

**Issue by devyuseon** [backtothefuture-team/backtothefuture-backend#114]
## Description
- `@RequestParts`, `@ModelAttribute` 같은 non-json api 에 대해 Spring REST Docs + OAS로 구현이 어려워 전환
-  rest assured 사용(#115 )으로, mockmvc 의존성 삭제
- 세팅 후 기존 API 문서화 작성에 대한 것은 추후 논의.

### TODO
- [x] 기존 테스트코드 삭제 (동시성 테스트는 삭제하지 말것)
- [x] Swagger 설정 추가
- [x] 멀티모듈 Swagger 설정
